apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: "$MYREGISTRY/$MYNAMESPACE/$MYPROJECT:1"
        ports:
        - name: http-server
          containerPort: 8080